name: totaro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pyarrow
  - libcst
  - pandas=1.5.*
  - portaudio
  - ffmpeg
  - sox
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.2
      - alembic==1.14.1
      - antlr4-python3-runtime==4.9.3
      - asteroid-filterbanks==0.4.0
      - attrs==25.1.0
      - audioread==3.0.1
      - babel==2.17.0
      - braceexpand==0.1.7
      - certifi
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorlog==6.9.0
      - contourpy
      - customtkinter
      - cycler
      - cytoolz
      - datasets
      - decorator
      - dill
      - docopt
      - editdistance
      - einops
      - executing
      - filelock
      - fonttools
      - frozenlist
      - fsspec
      - greenlet
      - grpcio
      - gTTS
      - huggingface-hub
      - hydra-core
      - HyperPyYAML
      - idna
      - intervaltree
      - ipython
      - ipython_pygments_lexers
      - jedi
      - Jinja2
      - jiwer
      - joblib
      - julius
      - kiwisolver
      - lazy_loader
      - lhotse
      - librosa
      - lightning
      - lightning-utilities
      - lilcom
      - llvmlite
      - Mako
      - Markdown
      - markdown-it-py
      - MarkupSafe
      - matplotlib
      - matplotlib-inline
      - mdurl
      - mpmath
      - msgpack
      - multidict
      - multiprocess
      - networkx
      - numba
      - omegaconf
      - onnx
      - optuna
      - packaging
      - parso
      - pexpect
      - pillow
      - platformdirs
      - pooch
      - primePy
      - prompt_toolkit
      - propcache
      - protobuf
      - ptyprocess
      - pure_eval
      - pyannote.audio
      - pyannote.core
      - pyannote.database
      - pyannote.metrics
      - pyannote.pipeline
      - pygame
      - PyAudio
      - Pygments
      - pygtrie
      - pyparsing
      - python-dateutil
      - pytorch-lightning
      - pytorch-metric-learning
      - pyttsx3
      - pytz
      - PyYAML
      - RapidFuzz
      - regex
      - requests
      - rich
      - ruamel.yaml
      - ruamel.yaml.clib
      - safetensors
      - scikit-learn
      - scipy
      - semver
      - sentencepiece
      - setuptools
      - shellingham
      - six
      - sortedcontainers
      - sounddevice
      - soundfile
      - soxr
      - speechbrain
      - SQLAlchemy
      - stack-data
      - sympy
      - tabulate
      - tensorboard
      - tensorboard-data-server
      - tensorboardX
      - text-unidecode
      - threadpoolctl
      - tkcalendar
      - tokenizers
      - toolz
      - torch
      - torch-audiomentations
      - torch_pitch_shift
      - torchaudio
      - torchmetrics
      - tqdm
      - traitlets
      - transformers
      - triton
      - typer
      - TTS
      - typing_extensions
      - tzdata
      - urllib3
      - wcwidth
      - webdataset
      - Werkzeug
      - wget
      - wrapt
      - xxhash
      - yarl
      - nemo_toolkit[asr]

